"""Independent CondA A/Q audit. See the precommitted spec."""
from __future__ import annotations
import argparse
import csv
import hashlib
import itertools
import json
import platform
import subprocess
import sys
import time
from collections import defaultdict
from pathlib import Path

import numpy as np
import torch

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from src.nets import VecMLPL

ARMS = ["LR_a0p1_q0", "LR_a0p3_q0", "LR_a0p7_q0", "LR_a0p3_qp05"]
STEPS = [0, 200000, 1000000, 5000000]
LRS = [0.0001, 0.001, 0.005]
DTYPES = [torch.float64, torch.float32]
COORDS = ["row_centered", "whole", "free5"]
CHECKS, GROUPS, BATCHES, SEGMENTS, SOURCES, BACKUPS = {}, [], [], [], [], []
MUTATIONS = defaultdict(int)


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def double(x):
    return x.detach().to(torch.float64)


def center(x):
    return x - x.mean(dim=-1, keepdim=True)


def coords(x, kind):
    x = double(x)
    return center(x) if kind == "row_centered" else x[..., 15:] if kind == "free5" else x


def check(name, actual, expected, dtype, tol=None):
    a, b = torch.broadcast_tensors(double(actual), double(expected))
    err = (a - b).abs()
    if tol is None:
        c = 1e-10 if dtype == torch.float64 else 2e-5
        tol = c * (1 + b.abs())
    tol = torch.broadcast_to(torch.as_tensor(tol, dtype=torch.float64), err.shape)
    finite = torch.isfinite(a) & torch.isfinite(b) & torch.isfinite(tol)
    bad = ~finite | (err > tol)
    key = (str(dtype).split(".")[-1], name)
    st = CHECKS.setdefault(key, dict(dtype=key[0], check=name, count=0, failed=0,
                                  max_abs_error=0., max_tolerance_fraction=0.))
    st["count"] += err.numel()
    st["failed"] += int(bad.sum())
    st["max_abs_error"] = max(st["max_abs_error"], float(err.max()))
    st["max_tolerance_fraction"] = max(st["max_tolerance_fraction"], float((err / tol).max()))


def mutation(name, wrong, correct):
    MUTATIONS[name] += int(((wrong-correct).abs() > 1e-10*(1+correct.abs())).sum())


def writecsv(path, rows):
    rows = list(rows)
    if rows:
        with path.open("w", newline="") as f:
            w = csv.DictWriter(f, list(dict.fromkeys(k for row in rows for k in row)))
            w.writeheader()
            w.writerows(rows)


def save_raw(path, **arrays):
    np.savez_compressed(path, **{k: v.detach().cpu().numpy() if torch.is_tensor(v) else v
                               for k, v in arrays.items()})
    BACKUPS.append(dict(source="generated by analysis/aq_identity_0917/verify.py",
                        backup=str(path), bytes=path.stat().st_size, sha256=sha(path)))


def make_net(cp, dtype, repeats=1):
    state = {k: v.to(dtype).repeat((repeats,) + (1,)*(v.ndim-1)) for k,v in cp["net"].items()}
    r, h, d = state["W"].shape
    n = VecMLPL(r, [h], d, torch.Generator().manual_seed(0), "cpu",
                act=cp["activation"], act_alpha=cp["act_alpha"])
    n.load_state(state)
    return n


def support(cp, dtype):
    r = cp["net"]["W"].shape[0]
    bits = torch.tensor(list(itertools.product([0., 1.], repeat=5)))
    raw = torch.cat([cp["env"]["flip_state"][None].expand(32,-1,-1),
                     bits[:,None].expand(-1,r,-1)], dim=-1)
    t = cp["teacher"]
    # The original discrete teacher is evaluated in float32 in both audits.
    pre = torch.einsum("rhd,srd->srh", t["W"], raw) + t["b"]
    y = (((pre >= t["tau"]).float()*t["v"]).sum(-1)+t["cout"]).to(dtype)
    x = raw.to(dtype)
    if cp["centered_layers"][0]:
        x = x - cp["layer_means"][0].to(dtype)[None]
    return x,y


def independent_autograd(n, x, y):
    # No production forward, hand derivative, h, or budget formula.
    w,b,v,c = [p.detach().clone().requires_grad_() for p in (n.W,n.b,n.v,n.c)]
    z = (w*x[:,None]).sum(-1)+b
    a = torch.where(z > 0, z, n.act_alpha*z)
    if n.act == "leaky_off_p0p5":
        a = a+0.5
    f = (a*v).sum(-1)+c
    return torch.autograd.grad(((f-y)**2).sum(), (w,b,v,c))


def pre_step(n, x, y, dtype):
    z,a,f = n.forward(x)
    e = f-y
    grads = n.grads(x,z,a,e)
    k = torch.where(z>0, torch.ones_like(z), torch.full_like(z,n.act_alpha))
    u = 2*double(e)[:,None]*double(n.v)
    h = u*double(k)
    out = dict(z=double(z), a=double(a), e=double(e), h=h, u=u, k=double(k),
               W=double(n.W).clone(), v=double(n.v).clone(), b=double(n.b).clone())
    ag = independent_autograd(n,x,y)
    for name,prod,aut in zip(["W","b","v","c"],grads,ag):
        check("autograd_"+name,prod,aut,dtype)
    for kind in COORDS:
        wc,xc = coords(n.W,kind),coords(x,kind)
        zc = (wc*xc[:,None]).sum(-1)
        g = coords(ag[0],kind)
        A,Q = h*zc,h**2*xc.square().sum(-1)[:,None]
        check(kind+"/expanded_gradient",h[...,None]*xc[:,None],g,dtype)
        check(kind+"/A_vs_autograd",A,(wc*g).sum(-1),dtype)
        check(kind+"/Q_vs_autograd",Q,g.square().sum(-1),dtype)
    wc,xc = center(out["W"]),center(double(x))
    zc = (wc*xc[:,None]).sum(-1)
    S = u*out["a"]
    H = u*(out["z"]*out["k"]-out["a"])
    B = out["b"]*h
    C = out["W"].mean(-1)*double(x).sum(-1)[:,None]*h
    check("row_centered/A_SHBC",h*zc,S+H-B-C,dtype)
    out.update(zc=zc,S=S,H=H,B=B,C=C)
    if dtype == torch.float64:
        mutation("missing_MSE_factor_2",0.5*h*zc,h*zc)
        mutation("full_z_instead_of_centered_z",h*out["z"],h*zc)
        mutation("uncentered_input_in_Q",h**2*double(x).square().sum(-1)[:,None],
                 h**2*xc.square().sum(-1)[:,None])
        if n.act == "leaky_off_p0p5":
            mutation("missing_H_on_offset",S-B-C,h*zc)
    return out,grads


def post_step(n,x,before,lr,dtype,meta):
    arrays = {}
    for kind in COORDS:
        old,new,xc = coords(before["W"],kind),coords(n.W,kind),coords(x,kind)
        h = before["h"]
        zc = (old*xc[:,None]).sum(-1)
        A,Q = h*zc,h.square()*xc.square().sum(-1)[:,None]
        linear,quadratic = -2*lr*A,lr**2*Q
        predicted = linear+quadratic
        r0,r1 = old.square().sum(-1),new.square().sum(-1)
        observed = r1-r0
        dw = new-old
        dot,q_actual = (old*dw).sum(-1),dw.square().sum(-1)
        scale = 1+r0+r1+linear.abs()+quadratic
        tol = 64*torch.finfo(dtype).eps*scale
        tol64 = 64*torch.finfo(torch.float64).eps*scale
        check(kind+"/norm_budget",observed,predicted,dtype,tol)
        check(kind+"/actual_displacement_geometry",observed,2*dot+q_actual,dtype,tol64)
        check(kind+"/actual_linear",2*dot,linear,dtype,tol)
        check(kind+"/actual_quadratic",q_actual,quadratic,dtype,tol)
        coeff = torch.where(r0>0,dot/r0.clamp_min(1e-300),torch.zeros_like(r0))
        perpendicular = dw-coeff[...,None]*old
        check(kind+"/radial_orthogonal",observed,
              2*dot+coeff.square()*r0+perpendicular.square().sum(-1),dtype,tol64)
        resolved = predicted.abs()>tol
        mismatch = resolved & (torch.sign(predicted)!=torch.sign(observed))
        check(kind+"/sign_mismatch",mismatch.double(),torch.zeros_like(predicted),dtype)
        for branch,mask in [("positive",before["z"]>0),("negative",before["z"]<0),
                            ("zero",before["z"]==0)]:
            if not bool(mask.any()):
                continue
            GROUPS.append(dict(**meta,coordinate=kind,branch=branch,count=int(mask.sum()),
                A_positive=int((mask & (A>0)).sum()),A_negative=int((mask & (A<0)).sum()),
                linear_sum=float(linear[mask].sum()),quadratic_sum=float(quadratic[mask].sum()),
                predicted_sum=float(predicted[mask].sum()),observed_sum=float(observed[mask].sum()),
                max_abs_error=float((observed-predicted)[mask].abs().max()),
                resolved=int((mask & resolved).sum()),
                shrink=int((mask & resolved & (predicted<0)).sum()),
                grow=int((mask & resolved & (predicted>0)).sum()),
                sign_mismatch=int((mask & mismatch).sum())))
        arrays[kind] = dict(A=A,Q=Q,linear=linear,quadratic=quadratic,observed=observed,
                            predicted=predicted,tol=tol)
    return arrays


def batch_audit(cp,dtype,x,y,p,meta):
    s,r,d = x.shape
    h = p["h"].reshape(s,r,-1)
    xc = center(double(x))
    g_s = h[...,None]*xc[:,:,None]
    g_mean = g_s.mean(0)
    q_mean = g_mean.square().sum(-1)
    gram = torch.einsum("srd,trd->rst",xc,xc)
    q_pair = torch.einsum("srh,trh,rst->rh",h,h,gram)/s**2
    check("batch32/Q_pair_vs_mean_gradient",q_pair,q_mean,dtype)
    n = make_net(cp,dtype)
    w = n.W.clone().requires_grad_()
    z = (w[None]*x[:,:,None]).sum(-1)+n.b
    a = torch.where(z>0,z,n.act_alpha*z)
    if n.act == "leaky_off_p0p5":
        a = a+0.5
    pred = (a*n.v).sum(-1)+n.c
    ag = torch.autograd.grad(((pred-y)**2).mean(0).sum(),w)[0]
    check("batch32/gradient_vs_autograd",g_mean,center(double(ag)),dtype)
    check("batch32/Q_vs_autograd",q_pair,center(double(ag)).square().sum(-1),dtype)
    q_sample = g_s.square().sum(-1).mean(0)
    if dtype == torch.float64:
        mutation("mean_sample_Q_instead_of_batch_Q",q_sample,q_pair)
    BATCHES.append(dict(**meta,batch_size=s,Q_batch=float(q_pair.sum()),
                        Q_expected_batch1=float(q_sample.sum()),gap=float((q_sample-q_pair).sum())))


def frozen(cp,dtype,rawdir):
    x,y = support(cp,dtype)
    n = make_net(cp,dtype,repeats=32)
    xf,yf = x.reshape(-1,x.shape[-1]),y.flatten()
    pre,grads = pre_step(n,xf,yf,dtype)
    dn = str(dtype).split(".")[-1]
    meta = dict(phase="fixed",arm=cp["arm"],checkpoint=cp["step"],dtype=dn)
    batch_audit(cp,dtype,x,y,pre,meta)
    payload = {k: pre[k] for k in ["z","zc","e","h","S","H","B","C"]}
    payload.update(input=xf,W_old=n.W.clone())
    for lr in LRS:
        nn = make_net(cp,dtype,repeats=32)
        nn.sgd_step(torch.full((nn.R,),lr,dtype=dtype),*grads)
        values = post_step(nn,xf,pre,lr,dtype,dict(**meta,lr=lr))
        for kind,a in values.items():
            for key,val in a.items():
                payload[f"lr{lr}_{kind}_{key}"] = val
        payload[f"lr{lr}_W_new"] = nn.W.clone()
    save_raw(rawdir/f"{cp['arm']}_step{cp['step']}_{dn}_frozen.npz",**payload)


def continuation(cp,dtype,rawdir):
    x,y = support(cp,dtype)
    n = make_net(cp,dtype)
    start = n.W.clone()
    lr = float(cp["runs"][0]["lr"])
    rng = np.random.Generator(np.random.PCG64(20260917))
    dn = str(dtype).split(".")[-1]
    totals = {kind:{k:torch.zeros_like(double(n.b)) for k in ["linear","quadratic","tol"]}
              for kind in COORDS}
    records = defaultdict(list)
    run_idx = torch.arange(n.R)
    for t in range(256):
        idx = torch.as_tensor(rng.integers(0,32,size=n.R))
        xb,yb = x[idx,run_idx],y[idx,run_idx]
        pre,grads = pre_step(n,xb,yb,dtype)
        n.sgd_step(torch.full((n.R,),lr,dtype=dtype),*grads)
        meta = dict(phase="continuation",arm=cp["arm"],checkpoint=cp["step"],
                    dtype=dn,lr=lr,continuation_step=t)
        values = post_step(n,xb,pre,lr,dtype,meta)
        records["support_index"].append(idx)
        records["z"].append(pre["z"])
        for kind,a in values.items():
            for k in totals[kind]:
                totals[kind][k] += a[k]
            for k,v in a.items():
                records[f"{kind}_{k}"].append(v)
    for kind,a in totals.items():
        observed = coords(n.W,kind).square().sum(-1)-coords(start,kind).square().sum(-1)
        predicted = a["linear"]+a["quadratic"]
        check(kind+"/cumulative_budget",observed,predicted,dtype,a["tol"])
        SEGMENTS.append(dict(arm=cp["arm"],dtype=dn,coordinate=kind,steps=256,lr=lr,
            linear=float(a["linear"].sum()),quadratic=float(a["quadratic"].sum()),
            predicted=float(predicted.sum()),observed=float(observed.sum()),
            max_unit_error=float((observed-predicted).abs().max())))
    save_raw(rawdir/f"{cp['arm']}_{dn}_continuation.npz",W_start=start,W_end=n.W,
             **{k:torch.stack(v) for k,v in records.items()})


def finish(out,rawdir,started,code_head):
    checks = list(CHECKS.values())
    for name,rows in [("checks",checks),("groups",GROUPS),("continuations",SEGMENTS),("batch_checks",BATCHES)]:
        writecsv(out/f"{name}.csv",rows)
    required = ["missing_MSE_factor_2","full_z_instead_of_centered_z","uncentered_input_in_Q",
                "missing_H_on_offset","mean_sample_Q_instead_of_batch_Q"]
    coverage = {}
    for branch in ["positive","negative"]:
        rows = [r for r in GROUPS if r["dtype"]=="float64" and r["coordinate"]=="row_centered"
                and r["phase"]=="fixed" and r["branch"]==branch]
        coverage[branch] = {k:sum(r[k] for r in rows) for k in ["count","shrink","grow","sign_mismatch"]}
    failures = sum(r["failed"] for r in checks)
    covered = all(v["count"]>0 for v in coverage.values()) and all(
        sum(v[k] for v in coverage.values())>0 for k in ["shrink","grow"])
    mutation_ok = all(MUTATIONS[k]>0 for k in required)
    verdict = "FAIL" if failures or not mutation_ok else "PASS" if covered else "INCOMPLETE"
    verdict_rows = []
    for dtype in ["float64","float32"]:
        budget = next(r for r in checks if r["dtype"]==dtype and r["check"]=="row_centered/norm_budget")
        fixed = [r for r in GROUPS if r["phase"]=="fixed" and r["coordinate"]=="row_centered" and r["dtype"]==dtype]
        verdict_rows.append(dict(verdict=verdict,dtype=dtype,unit_updates=sum(r["count"] for r in fixed),
            max_norm_budget_error=budget["max_abs_error"],
            max_rounding_bound_fraction=budget["max_tolerance_fraction"],
            resolved=sum(r["resolved"] for r in fixed),shrink=sum(r["shrink"] for r in fixed),
            grow=sum(r["grow"] for r in fixed),sign_mismatch=sum(r["sign_mismatch"] for r in fixed),
            check_failures=sum(r["failed"] for r in checks if r["dtype"]==dtype)))
    writecsv(out/"verdict.csv",verdict_rows)
    (out/"controls.json").write_text(json.dumps(dict(mutation_detected_counts=dict(MUTATIONS),coverage=coverage),indent=2))
    (out/"backup_manifest.json").write_text(json.dumps(BACKUPS,indent=2))
    (out/"provenance.json").write_text(json.dumps(dict(run_id="aq_identity_0917",git_hash=code_head,
        registration_commit="c7df571",python=sys.version,torch=torch.__version__,numpy=np.__version__,
        platform=platform.platform(),elapsed_seconds=time.time()-started,raw_directory=str(rawdir),
        input_checkpoints=SOURCES,source_sha256={str(p.relative_to(ROOT)):sha(p) for p in
        [Path(__file__),ROOT/"src/nets.py",ROOT/"src/envs.py",ROOT/"specs/spec_aq_identity_0917.md"]},
        meaning="Fixed-state arithmetic audit and short fixed-task continuations, not long-run mechanism evidence"),indent=2))
    text = ["# CondA A/Q identity audit","",f"Verdict: **{verdict}**","",
        "Registered audit on previously studied checkpoints. 4 leaky arms × 4 checkpoints × 10 seeds × 32 input support points; 100 units, three fixed-state learning rates, two dtypes. Also 256-step fixed-task continuations from step 200000 for each arm/dtype.","",
        "Full W, row-centered W, and CondA's free five coordinates are distinct. Results below use row centering unless stated otherwise.","",
        "| dtype | fixed-state unit updates | max absolute budget error (incl. continuations) | max error / rounding bound | resolved signs | sign mismatches |",
        "|---|---:|---:|---:|---:|---:|"]
    for r in verdict_rows:
        text.append(f"| {r['dtype']} | {r['unit_updates']} | {r['max_norm_budget_error']:.9g} | {r['max_rounding_bound_fraction']:.6g} | {r['resolved']} | {r['sign_mismatch']} |")
    text += ["","## What was checked","",
        "Expanded residual/readout/gate/input formulas were compared with an independent autograd network; A, Q, S+H-B-C, production handwritten gradients, actual optimizer displacement, radial/orthogonal geometry, and accumulated short-segment budgets were checked separately. The 32-sample Gram formula was compared with an independently differentiated full-batch loss.","",
        f"Total failed scalar checks: {failures}. Mutation controls: {dict(MUTATIONS)}.","",
        "## Pre-update branches (float64, fixed-state probes)","",
        "Counts pool checkpoint/seed/sample/unit/lr probe events, not independent experimental replicates or longitudinal unit fates.","",
        "| branch | events | significant shrink | significant growth | sign mismatch |","|---|---:|---:|---:|---:|"]
    for branch,r in coverage.items():
        text.append(f"| {branch} | {r['count']} | {r['shrink']} | {r['grow']} | {r['sign_mismatch']} |")
    text += ["","## Short continuation budgets (row-centered, sum over saved seeds/units)","",
        "Newly sampled 256-step fixed-task continuations, not original-stream replays or complete tasks.","",
        "| arm | dtype | linear contribution | quadratic contribution | observed endpoint change | max unit discrepancy |",
        "|---|---|---:|---:|---:|---:|"]
    for r in SEGMENTS:
        if r["coordinate"]=="row_centered":
            text.append(f"| {r['arm']} | {r['dtype']} | {r['linear']:.9g} | {r['quadratic']:.9g} | {r['observed']:.9g} | {r['max_unit_error']:.6g} |")
    text += ["","## Limits","",
        "- PASS validates the identity and implementation mapping, not a general branch-specific contraction mechanism, long-run learning-rate dependence, or LoP causality.",
        "- Float32 updates round; changes below the registered bound are unresolved, not sign matches. Float64 diagnostics on stored native weights avoid extra float32 norm-reduction cancellation.",
        "- Full-batch Q is squared mean gradient, not mean squared sample gradient. Expected batch-1 Q uses the latter.",
        "- Positive z does not imply positive centered zc. Replacing zc by z is a rejected control.",
        "- Every learning-rate probe starts from the same checkpoint; this is not an equal-horizon learning-rate training sweep.","",
        "Reproduce: OMP_NUM_THREADS=1 python3 analysis/aq_identity_0917/verify.py",
        "Complete per-unit arrays and input hashes are indexed by backup_manifest.json and provenance.json."]
    (out/"summary.md").write_text("\n".join(text)+"\n")
    print(json.dumps(dict(verdict=verdict,failures=failures,mutation_ok=mutation_ok,coverage=coverage,
                         elapsed=time.time()-started)),flush=True)
    return verdict


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--checkpoints",type=Path,default=Path("/home/issan/Projects/obsidian-research-data/zero_attraction_0913/training/ckpts"))
    ap.add_argument("--raw",type=Path,default=Path("/home/issan/Projects/obsidian-research-data/aq_identity_0917/raw"))
    args = ap.parse_args()
    torch.set_num_threads(1)
    out = ROOT/"results/aq_identity_0917"
    out.mkdir(parents=True,exist_ok=True)
    args.raw.mkdir(parents=True,exist_ok=True)
    started = time.time()
    head = subprocess.check_output(["git","rev-parse","HEAD"],cwd=ROOT,text=True).strip()
    for arm in ARMS:
        for step in STEPS:
            path = args.checkpoints/f"{arm}_step{step}.pt"
            SOURCES.append(dict(path=str(path),bytes=path.stat().st_size,sha256=sha(path)))
            cp = torch.load(path,map_location="cpu",weights_only=True)
            for dtype in DTYPES:
                frozen(cp,dtype,args.raw)
                if step==200000:
                    continuation(cp,dtype,args.raw)
            print(f"audited {arm} checkpoint {step}",flush=True)
    return 0 if finish(out,args.raw,started,head)=="PASS" else 1


if __name__=="__main__":
    raise SystemExit(main())
